const KEY='property-roi-tracker-v3';
const LEGACY='property-roi-tracker-v1';
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(Number(n)||0);
const pct=n=>`${Number(n||0).toFixed(1)}%`;
const num=v=>Number(v)||0;
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
const frequencies={weekly:52,fortnightly:26,monthly:12,quarterly:4,'half-yearly':2,annual:1,'one-off':0};
let state=load(); let route={name:'portfolio'};

function blank(){return {version:3,properties:[]}}
function migrate(x){
  const list=Array.isArray(x)?x:(x?.properties||[]);
  return {version:3,properties:list.map(p=>({
    id:p.id||uid(),address:p.address||p.name||'',suburb:p.suburb||'',city:p.city||'',state:p.state||'',postcode:p.postcode||'',
    purchaseDate:p.purchaseDate||'',purchasePrice:num(p.purchasePrice),acquisitionCosts:num(p.acquisitionCosts||p.purchaseCosts),
    currentValue:num(p.currentValue||p.value),loanBalance:num(p.loanBalance||p.loan),interestRate:num(p.interestRate),annualPrincipal:num(p.annualPrincipal),
    rentAmount:num(p.rentAmount||p.weeklyRent),rentFrequency:p.rentFrequency||(p.weeklyRent?'weekly':'weekly'),vacancyWeeks:num(p.vacancyWeeks),
    sellingAgentPct:num(p.sellingAgentPct||2.2),sellingFixedCosts:num(p.sellingFixedCosts||5000),
    expenses:(p.expenses||[]).map(e=>({id:e.id||uid(),name:e.name||e.category||'Expense',payee:e.payee||'',amount:num(e.amount),frequency:e.frequency||'annual',type:e.type||'operating',nextDueDate:e.nextDueDate||'',reminderDays:num(e.reminderDays??14),lastPaidDate:e.lastPaidDate||'',paid:!!e.paid,notes:e.notes||''})),
    valuations:p.valuations||[],prospects:{priceGrowth:num(p.prospects?.priceGrowth),rentGrowth:num(p.prospects?.rentGrowth),vacancyRate:num(p.prospects?.vacancyRate),populationGrowth:num(p.prospects?.populationGrowth),supply:p.prospects?.supply||'balanced',infrastructure:p.prospects?.infrastructure||'neutral',sourceDate:p.prospects?.sourceDate||'',notes:p.prospects?.notes||''},
    strategy:{growthConservative:num(p.strategy?.growthConservative||2),growthBase:num(p.strategy?.growthBase||p.prospects?.priceGrowth||5),growthOptimistic:num(p.strategy?.growthOptimistic||7),growthMethod:p.strategy?.growthMethod||'manual',suburbHistoryStart:num(p.strategy?.suburbHistoryStart),suburbHistoryEnd:num(p.strategy?.suburbHistoryEnd),suburbHistoryYears:num(p.strategy?.suburbHistoryYears||10),rentGrowth:num(p.strategy?.rentGrowth||p.prospects?.rentGrowth||3),expenseGrowth:num(p.strategy?.expenseGrowth||3),interestRate:num(p.strategy?.interestRate||p.interestRate),annualDebtReduction:num(p.strategy?.annualDebtReduction||p.annualPrincipal),forecastYears:num(p.strategy?.forecastYears||10),sellYear:num(p.strategy?.sellYear||0),cgtRate:num(p.strategy?.cgtRate),redeployReturn:num(p.strategy?.redeployReturn||6),saleValueHaircut:num(p.strategy?.saleValueHaircut),developmentEnabled:!!p.strategy?.developmentEnabled,developmentMonths:num(p.strategy?.developmentMonths||24),developmentEndValue:num(p.strategy?.developmentEndValue),developmentCosts:num(p.strategy?.developmentCosts),developmentEquity:num(p.strategy?.developmentEquity)}
  }))};
}
function load(){try{const v=localStorage.getItem(KEY);if(v)return migrate(JSON.parse(v));const old=localStorage.getItem(LEGACY);if(old){const m=migrate(JSON.parse(old));localStorage.setItem(KEY,JSON.stringify(m));return m}}catch(e){}return blank()}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function annualExpense(e){return num(e.amount)*(frequencies[e.frequency]??1)}
function calc(p){
  const grossRent=num(p.rentAmount)*(frequencies[p.rentFrequency]??52);
  const annualIncome=p.rentFrequency==='weekly'?num(p.rentAmount)/7*365:grossRent;
  const rent=grossRent*(1-Math.min(52,num(p.vacancyWeeks))/52);
  const op=p.expenses.filter(e=>e.type!=='capital').reduce((a,e)=>a+annualExpense(e),0);
  const capex=p.expenses.filter(e=>e.type==='capital').reduce((a,e)=>a+annualExpense(e),0);
  const interest=num(p.loanBalance)*num(p.interestRate)/100;
  const cash=rent-op-interest-num(p.annualPrincipal);
  const growth=recentGrowth(p);
  const growthDollars=num(p.currentValue)*growth/100;
  const sellCosts=num(p.currentValue)*num(p.sellingAgentPct)/100+num(p.sellingFixedCosts);
  const equity=num(p.currentValue)-num(p.loanBalance);
  const saleEquity=equity-sellCosts;
  const purchaseBasis=num(p.purchasePrice)+num(p.acquisitionCosts);
  return {grossRent,annualIncome,purchaseBasis,purchaseRoe:purchaseBasis>0?annualIncome/purchaseBasis*100:0,rent,op,capex,interest,cash,growth,growthDollars,sellCosts,equity,saleEquity,lvr:p.currentValue?p.loanBalance/p.currentValue*100:0,grossYield:p.currentValue?grossRent/p.currentValue*100:0,netYield:p.currentValue?(rent-op)/p.currentValue*100:0,cashRoe:saleEquity>0?cash/saleEquity*100:0,totalRoe:saleEquity>0?(cash+growthDollars)/saleEquity*100:0};
}
function recentGrowth(p){const vals=[...(p.valuations||[]),...(p.currentValue&&p.valuationDate?[{date:p.valuationDate,value:p.currentValue}]:[])].filter(v=>v.date&&num(v.value)).sort((a,b)=>a.date.localeCompare(b.date));if(vals.length>1){const a=vals[0],b=vals.at(-1),years=(new Date(b.date)-new Date(a.date))/31557600000;if(years>0)return (Math.pow(num(b.value)/num(a.value),1/years)-1)*100}return num(p.prospects?.priceGrowth)}
function suburbCagr(p){const s=p.strategy||{},start=num(s.suburbHistoryStart),end=num(s.suburbHistoryEnd),years=num(s.suburbHistoryYears);return start>0&&end>0&&years>0?(Math.pow(end/start,1/years)-1)*100:0}
function forecastRate(p){const s=p.strategy||{},historical=suburbCagr(p);return s.growthMethod==='historical'&&historical?historical:num(s.growthBase)}
function forecast(p,growth){const s=p.strategy||{},base=calc(p),years=Math.max(1,Math.min(30,num(s.forecastYears)||10)),rows=[];for(let y=0;y<=years;y++){const value=num(p.currentValue)*Math.pow(1+growth/100,y);const debt=Math.max(0,num(p.loanBalance)-num(s.annualDebtReduction)*y);const rent=base.rent*Math.pow(1+num(s.rentGrowth)/100,y);const op=base.op*Math.pow(1+num(s.expenseGrowth)/100,y);const interest=debt*num(s.interestRate)/100;const cash=rent-op-interest-num(s.annualDebtReduction);const costs=value*num(p.sellingAgentPct)/100+num(p.sellingFixedCosts);const saleEquity=value*(1-num(s.saleValueHaircut)/100)-debt-costs;const roe=saleEquity>0?(cash+value*growth/100)/saleEquity*100:0;rows.push({y,value,debt,rent,op,interest,cash,saleEquity,roe})}return rows}
function saleScenario(p){const s=p.strategy||{},year=Math.max(0,Math.min(num(s.sellYear),num(s.forecastYears)||10));if(!year)return null;const row=forecast(p,forecastRate(p))[year];const gain=Math.max(0,row.value*(1-num(s.saleValueHaircut)/100)-num(p.purchasePrice)-num(p.acquisitionCosts));const tax=gain*num(s.cgtRate)/100;const net=Math.max(0,row.saleEquity-tax);const horizon=Math.max(0,(num(s.forecastYears)||10)-year);return {year,row,gain,tax,net,future:net*Math.pow(1+num(s.redeployReturn)/100,horizon),horizon}}
function input(name,label,value='',type='text',extra='',full=''){return `<div class="field ${full}"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${extra}></div>`}
function select(name,label,value,opts){return `<div class="field"><label for="${name}">${label}</label><select id="${name}" name="${name}">${opts.map(([v,l])=>`<option value="${v}" ${v===value?'selected':''}>${l}</option>`).join('')}</select></div>`}
function section(t){return `<div class="form-section">${t}</div>`}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}

function render(){
  document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===route.name));
  const detail=route.name==='property';$('#backBtn').classList.toggle('hidden',!detail);$('#headerAction').classList.toggle('hidden',route.name!=='portfolio');
  if(route.name==='portfolio')renderPortfolio(); else if(detail)renderProperty(); else if(route.name==='backup')renderBackup(); else renderAbout();
}
function renderPortfolio(){
  $('#pageTitle').textContent='Overview';const totals=state.properties.reduce((a,p)=>{const c=calc(p);a.value+=num(p.currentValue);a.debt+=num(p.loanBalance);a.equity+=c.equity;a.cash+=c.cash;a.saleEquity+=c.saleEquity;a.ret+=c.cash+c.growthDollars;return a},{value:0,debt:0,equity:0,cash:0,saleEquity:0,ret:0});
  $('#app').innerHTML=`<section class="hero"><div class="label">Current portfolio value</div><div class="value">${money(totals.value)}</div><div class="metrics"><div><div class="label">Debt</div><b>${money(totals.debt)}</b></div><div><div class="label">Equity</div><b>${money(totals.equity)}</b></div><div><div class="label">LVR</div><b>${pct(totals.value?totals.debt/totals.value*100:0)}</b></div><div><div class="label">Current ROE</div><b>${pct(totals.saleEquity?totals.ret/totals.saleEquity*100:0)}</b></div></div></section><div class="section-head"><h2>Your properties</h2><span>${state.properties.length} total</span></div><div class="property-list">${state.properties.map(card).join('')||`<div class="panel empty">No properties yet.<br><br><button class="primary" data-add>Add your first property</button></div>`}</div>`;
  document.querySelectorAll('[data-property]').forEach(b=>b.onclick=()=>{route={name:'property',id:b.dataset.property};render();scrollTo(0,0)});document.querySelector('[data-add]')?.addEventListener('click',()=>openProperty());
}
function card(p){const c=calc(p);return `<button class="property-card" data-property="${p.id}"><div class="card-top"><div><div class="address">${esc(p.address||'Unnamed property')}</div><div class="location">${esc([p.suburb,p.state].filter(Boolean).join(', '))}</div></div><span class="chev">›</span></div><div class="card-stats"><div><small>VALUE</small><b>${money(p.currentValue)}</b></div><div><small>SALE EQUITY</small><b>${money(c.saleEquity)}</b></div><div><small>CURRENT ROE</small><b class="${c.totalRoe<0?'negative':'positive'}">${pct(c.totalRoe)}</b></div></div></button>`}
function metric(label,value,small='',cls=''){return `<div class="metric"><div class="label">${label}</div><div class="value ${cls}">${value}</div>${small?`<small>${small}</small>`:''}</div>`}
function renderProperty(){const p=state.properties.find(x=>x.id===route.id);if(!p){route={name:'portfolio'};return render()}const c=calc(p);$('#pageTitle').textContent=p.address||'Property';const pros=prospect(p),s=p.strategy||{},historicalCagr=suburbCagr(p),baseRate=forecastRate(p),fc=forecast(p,num(s.growthConservative)),fb=forecast(p,baseRate),fo=forecast(p,num(s.growthOptimistic)),sale=saleScenario(p),end=fb.at(-1),devProfit=num(s.developmentEndValue)-num(s.developmentCosts),devMdc=s.developmentCosts?devProfit/num(s.developmentCosts)*100:0,devAnnual=s.developmentEquity&&s.developmentMonths?devProfit/num(s.developmentEquity)*12/num(s.developmentMonths)*100:0;$('#app').innerHTML=`
  <div class="actions" style="margin-bottom:12px"><button class="primary" data-edit>Edit all inputs</button><button class="secondary" data-value>+ Valuation</button><button class="secondary" data-expense>+ Expense</button></div>
  <section class="hero"><div class="label">Estimated value today</div><div class="value">${money(p.currentValue)}</div><div class="metrics">${metric('Loan',money(p.loanBalance))}${metric('Gross equity',money(c.equity))}${metric('Selling costs',money(c.sellCosts))}${metric('Net sale equity',money(c.saleEquity),'Value − debt − selling costs')}</div></section>
  <div class="panel"><h2>Return on current equity</h2><div class="metrics">${metric('Current ROE',pct(c.totalRoe),'Cash return + annualised growth ÷ net sale equity',c.totalRoe<0?'negative':'positive')}${metric('Cash-only ROE',pct(c.cashRoe),'Annual cash flow ÷ net sale equity',c.cashRoe<0?'negative':'positive')}${metric('Annual cash flow',money(c.cash),'Before capital expenditure',c.cash<0?'negative':'positive')}${metric('Growth used',pct(c.growth),c.growth?'From valuation history / market input':'No growth assumed')}</div><p class="subtle">Net sale equity answers “what could be released if sold today?” Tax is excluded because individual circumstances vary.</p></div>
  <div class="detail-grid"><div class="panel"><h2>Income & expenses</h2><div class="metrics">${metric('Annual rent',money(c.rent))}${metric('Operating costs',money(c.op))}${metric('Interest',money(c.interest))}${metric('Capital spend',money(c.capex))}${metric('Gross yield',pct(c.grossYield))}${metric('Net yield',pct(c.netYield))}</div><div class="section-head"><h3>Expense register</h3><span>${p.expenses.length} items</span></div>${p.expenses.map(e=>`<div class="expense-row"><div><b>${esc(e.name)}</b><small>${esc(e.type)} · ${esc(e.frequency)}</small></div><div><b>${money(annualExpense(e))}/yr</b><div class="expense-actions"><button data-edit-exp="${e.id}">Edit</button><button data-del-exp="${e.id}">Delete</button></div></div></div>`).join('')||'<p class="subtle">No expenses entered.</p>'}</div>
  <div class="panel"><h2>Property facts</h2><div class="source-row"><span>Location</span><b>${esc([p.suburb,p.city,p.state,p.postcode].filter(Boolean).join(', '))}</b></div><div class="source-row"><span>Purchase</span><b>${money(p.purchasePrice)}</b></div><div class="source-row"><span>LVR</span><b>${pct(c.lvr)}</b></div><div class="source-row"><span>Interest rate</span><b>${pct(p.interestRate)}</b></div><div class="source-row"><span>Vacancy allowance</span><b>${num(p.vacancyWeeks)} weeks</b></div></div></div>
  <div class="panel purchase-roe"><h2>Purchase-basis ROE</h2><div class="metrics">${metric('ROE',pct(c.purchaseRoe),'One year gross rental income ÷ purchase basis','positive')}${metric('Annual income',money(c.annualIncome),p.rentFrequency==='weekly'?'Weekly rent ÷ 7 × 365':'Annualised from entered frequency')}${metric('Purchase price',money(p.purchasePrice))}${metric('Purchase costs',money(p.acquisitionCosts))}</div><div class="formula-box">${money(p.rentAmount)} weekly ÷ 7 × 365 = ${money(c.annualIncome)}<br>${money(c.annualIncome)} ÷ (${money(p.purchasePrice)} + ${money(p.acquisitionCosts)}) = <b>${pct(c.purchaseRoe)}</b></div><p class="subtle">This is a gross purchase-basis return. It does not deduct vacancy, expenses, interest or tax. Current-equity ROE above remains the sell-today measure.</p></div>
  <div class="panel suburb-growth"><div class="panel-head"><h2>Suburb capital-growth analysis</h2><button class="secondary" data-edit>Edit forecast</button></div><div class="metrics">${metric('Historical start',money(s.suburbHistoryStart),`${s.suburbHistoryYears} years ago`)}${metric('Historical end',money(s.suburbHistoryEnd),'Current suburb benchmark')}${metric('Historical CAGR',pct(historicalCagr),'Compound annual growth')}${metric('Forecast rate used',pct(baseRate),s.growthMethod==='historical'?'Historical CAGR selected':'Manual suburb forecast')}</div><div class="formula-box">Forecast value = current property value × (1 + ${pct(baseRate)})<sup>${s.forecastYears} years</sup><br><b>${money(p.currentValue)} → ${money(end.value)}</b></div><p class="subtle">Use comparable suburb data over a meaningful period. Historical growth is evidence for an assumption, not a guarantee of future growth.</p></div>
  ${s.developmentEnabled?`<div class="panel"><div class="panel-head"><h2>Development feasibility</h2><button class="secondary" data-edit>Edit project</button></div><div class="metrics">${metric('End value / revenue',money(s.developmentEndValue))}${metric('Total development cost',money(s.developmentCosts))}${metric('Projected profit',money(devProfit),'Before tax',devProfit<0?'negative':'positive')}${metric('Margin on cost',pct(devMdc))}${metric('Equity contribution',money(s.developmentEquity))}${metric('Annualised cash return',pct(devAnnual),`${s.developmentMonths} month project`)}</div><p class="subtle">Enter total costs inclusive of acquisition, consultants, approvals, construction, contingency, finance, GST and selling/leasing costs. This is a high-level feasibility, not a quantity survey or tax model.</p></div>`:''}
  <div class="panel"><div class="panel-head"><h2>Strategy & future value</h2><button class="secondary" data-edit>Change assumptions</button></div><p class="subtle">Scenario projections are assumptions, not valuations. Figures are nominal and before personal tax unless shown.</p><div class="scenario-grid"><div class="scenario"><small>CONSERVATIVE · ${pct(s.growthConservative)}</small><b>${money(fc.at(-1).value)}</b><span>in ${s.forecastYears} years</span></div><div class="scenario featured"><small>BASE · ${pct(s.growthBase)}</small><b>${money(end.value)}</b><span>in ${s.forecastYears} years</span></div><div class="scenario"><small>OPTIMISTIC · ${pct(s.growthOptimistic)}</small><b>${money(fo.at(-1).value)}</b><span>in ${s.forecastYears} years</span></div></div><div class="forecast-scroll"><table><thead><tr><th>Year</th><th>Value</th><th>Debt</th><th>Net sale equity</th><th>Rent p.a.</th><th>Cash flow</th><th>ROE</th></tr></thead><tbody>${fb.filter((r,i)=>i===0||i===fb.length-1||i%5===0).map(r=>`<tr><td>${r.y===0?'Today':r.y}</td><td>${money(r.value)}</td><td>${money(r.debt)}</td><td>${money(r.saleEquity)}</td><td>${money(r.rent)}</td><td class="${r.cash<0?'negative':'positive'}">${money(r.cash)}</td><td>${pct(r.roe)}</td></tr>`).join('')}</tbody></table></div><div class="metrics strategy-metrics">${metric('Projected value',money(end.value),`Base case, year ${s.forecastYears}`)}${metric('Projected debt',money(end.debt),`${money(s.annualDebtReduction)}/yr reduction`)}${metric('Projected equity',money(end.saleEquity),'After estimated sale costs')}${metric('Projected rent',money(end.rent),'Annual rent after growth')}</div>${sale?`<div class="sale-box"><div class="panel-head"><h3>Sell in year ${sale.year}</h3><span class="pill">MODELLING ONLY</span></div><div class="metrics">${metric('Sale value',money(sale.row.value))}${metric('Estimated tax',money(sale.tax),`${pct(s.cgtRate)} effective assumption`)}${metric('Net cash released',money(sale.net),'After debt, selling costs and tax')}${metric(`Redeployed by year ${s.forecastYears}`,money(sale.future),`${pct(s.redeployReturn)} return for ${sale.horizon} years`)}</div></div>`:`<div class="callout">Set a proposed sale year to compare holding with selling and redeploying the released capital.</div>`}</div>
  <div class="panel"><div class="panel-head"><h2>Open-source market prospects</h2><button class="secondary" data-edit>Edit indicators</button></div><div class="prospect-score"><div class="score-orb" style="--score:${pros.score}"><span>${pros.score}</span></div><div><b>${pros.label}</b><div class="subtle">Directional indicator, not a forecast</div></div></div><p class="analysis">${pros.text}</p>${p.prospects?.notes?`<div class="callout">${esc(p.prospects.notes)}</div>`:''}<div class="metrics">${metric('Price growth',pct(p.prospects?.priceGrowth),'12-month / selected period')}${metric('Rent growth',pct(p.prospects?.rentGrowth))}${metric('Vacancy',pct(p.prospects?.vacancyRate))}${metric('Population',pct(p.prospects?.populationGrowth))}</div><div class="section-head"><h3>Research links</h3><span>Verify before relying</span></div>${sources(p).map(s=>`<div class="source-row"><div><a href="${s.url}" target="_blank" rel="noopener">${s.name}</a><small>${s.use}</small></div><span>↗</span></div>`).join('')}<p class="subtle">Indicator date: ${esc(p.prospects?.sourceDate||'not recorded')}. Data is entered manually; the app does not imply these links endorse the analysis.</p></div>
  <div class="panel"><h2>Valuation history</h2>${(p.valuations||[]).sort((a,b)=>b.date.localeCompare(a.date)).map(v=>`<div class="history-row"><span>${esc(v.date)} <small class="subtle">${esc(v.source||'Manual')}</small></span><b>${money(v.value)}</b></div>`).join('')||'<p class="subtle">Add valuations to calculate annualised growth from actual history.</p>'}</div>
  <div class="actions"><button class="secondary" data-edit>Edit property</button><button class="danger" data-delete>Delete property</button></div>`;
  document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProperty(p));$('[data-expense]').onclick=()=>openExpense(p);$('[data-value]').onclick=()=>openValuation(p);$('[data-delete]').onclick=()=>{if(confirm('Delete this property and all its history?')){state.properties=state.properties.filter(x=>x.id!==p.id);save();route={name:'portfolio'};render()}};
  document.querySelectorAll('[data-edit-exp]').forEach(b=>b.onclick=()=>openExpense(p,p.expenses.find(e=>e.id===b.dataset.editExp)));document.querySelectorAll('[data-del-exp]').forEach(b=>b.onclick=()=>{if(confirm('Delete this expense?')){p.expenses=p.expenses.filter(e=>e.id!==b.dataset.delExp);save();render()}});
}
function prospect(p){const x=p.prospects||{};let raw=50+num(x.priceGrowth)*2+num(x.rentGrowth)*1.5-num(x.vacancyRate)*4+num(x.populationGrowth)*3+(x.supply==='tight'?10:x.supply==='high'?-10:0)+(x.infrastructure==='positive'?8:x.infrastructure==='negative'?-8:0);const score=Math.max(0,Math.min(100,Math.round(raw)));const label=score>=70?'Stronger indicators':score>=45?'Mixed / balanced indicators':'Weaker indicators';const parts=[];parts.push(num(x.priceGrowth)>=5?'Recorded price momentum is positive.':num(x.priceGrowth)<0?'Recorded prices are declining.':'Recorded price movement is modest.');parts.push(num(x.rentGrowth)>=5?'Rent growth supports income prospects.':'Rent growth provides limited support.');parts.push(num(x.vacancyRate)&&num(x.vacancyRate)<2?'Low vacancy suggests tight rental supply.':num(x.vacancyRate)>3?'Higher vacancy may weaken rental conditions.':'Vacancy appears broadly balanced or is not entered.');parts.push('This is a rules-based interpretation of the figures entered, not investment advice.');return {score,label,text:parts.join(' ')}}
function sources(p){const q=encodeURIComponent(`${p.suburb} ${p.state}`);return [{name:'Australian Bureau of Statistics',use:'Population, building approvals, Census and regional economy',url:'https://www.abs.gov.au/'},{name:'RBA statistics',use:'Rates, inflation, housing credit and economic context',url:'https://www.rba.gov.au/statistics/'},{name:'State planning portal',use:'Planning proposals, zoning and infrastructure pipeline',url:`https://www.google.com/search?q=${q}+state+planning+portal`},{name:'SQM Research free data',use:'Asking prices, rents and vacancy series (coverage varies)',url:'https://sqmresearch.com.au/'}]}

function openProperty(p=null){const f=$('#propertyForm'),x=p||migrate([{id:uid()}]).properties[0];f.innerHTML=`<div class="form-head"><h2>${p?'Edit property':'Add property'}</h2><button value="cancel" class="icon-btn">×</button></div><div class="form-grid">${section('PROPERTY & LOCATION')}${input('address','Street address',x.address,'text','required','full')}${input('suburb','Suburb',x.suburb)}${input('city','City / region',x.city)}${input('state','State / territory',x.state)}${input('postcode','Postcode',x.postcode,'text','inputmode="numeric"')}${section('PURCHASE & VALUE')}${input('purchaseDate','Purchase date',x.purchaseDate,'date')}${input('purchasePrice','Purchase price',x.purchasePrice,'number','min="0" step="1000"')}${input('acquisitionCosts','Acquisition costs',x.acquisitionCosts,'number','min="0"')}${input('currentValue','Current sale value',x.currentValue,'number','min="0" step="1000" required')}${section('LOAN & INCOME')}${input('loanBalance','Current loan balance',x.loanBalance,'number','min="0"')}${input('interestRate','Interest rate %',x.interestRate,'number','min="0" step="0.01"')}${input('annualPrincipal','Principal repayments / year',x.annualPrincipal,'number','min="0"')}${input('rentAmount','Rent amount',x.rentAmount,'number','min="0"')}${select('rentFrequency','Rent frequency',x.rentFrequency,[['weekly','Weekly'],['fortnightly','Fortnightly'],['monthly','Monthly'],['annual','Annual']])}${input('vacancyWeeks','Vacancy allowance (weeks/year)',x.vacancyWeeks,'number','min="0" max="52" step="0.5"')}${section('SALE TODAY ASSUMPTIONS')}${input('sellingAgentPct','Agent / selling fee %',x.sellingAgentPct,'number','min="0" step="0.1"')}${input('sellingFixedCosts','Fixed sale costs',x.sellingFixedCosts,'number','min="0"')}${section('OPEN-SOURCE MARKET INDICATORS')}${input('priceGrowth','Price growth %',x.prospects?.priceGrowth,'number','step="0.1"')}${input('rentGrowth','Rent growth %',x.prospects?.rentGrowth,'number','step="0.1"')}${input('vacancyRate','Vacancy rate %',x.prospects?.vacancyRate,'number','min="0" step="0.1"')}${input('populationGrowth','Population growth %',x.prospects?.populationGrowth,'number','step="0.1"')}${select('supply','Housing supply',x.prospects?.supply||'balanced',[['tight','Tight'],['balanced','Balanced / unknown'],['high','High pipeline']])}${select('infrastructure','Infrastructure signal',x.prospects?.infrastructure||'neutral',[['positive','Positive'],['neutral','Neutral / unknown'],['negative','Negative']])}${input('sourceDate','Data checked date',x.prospects?.sourceDate,'date')}<div class="field full"><label for="notes">Research notes / sources used</label><textarea id="notes" name="notes">${esc(x.prospects?.notes)}</textarea></div></div><div class="form-actions"><button value="cancel" class="secondary">Cancel</button><button value="default" class="primary">Save property</button></div>`;
  f.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(f));const target=p||x;['purchasePrice','acquisitionCosts','currentValue','loanBalance','interestRate','annualPrincipal','rentAmount','vacancyWeeks','sellingAgentPct','sellingFixedCosts'].forEach(k=>d[k]=num(d[k]));Object.assign(target,d);target.prospects={priceGrowth:num(d.priceGrowth),rentGrowth:num(d.rentGrowth),vacancyRate:num(d.vacancyRate),populationGrowth:num(d.populationGrowth),supply:d.supply,infrastructure:d.infrastructure,sourceDate:d.sourceDate,notes:d.notes};['priceGrowth','rentGrowth','vacancyRate','populationGrowth','supply','infrastructure','sourceDate','notes'].forEach(k=>delete target[k]);if(!p)state.properties.push(target);save();$('#propertyDialog').close();route={name:'property',id:target.id};render();toast('Property saved')};$('#propertyDialog').showModal();
}
function openExpense(p,e=null){const f=$('#expenseForm'),x=e||{id:uid(),name:'',amount:0,frequency:'annual',type:'operating'};f.innerHTML=`<div class="form-head"><h2>${e?'Edit':'Add'} expense</h2><button value="cancel" class="icon-btn">×</button></div><div class="form-grid">${input('name','Expense name',x.name,'text','required','full')}${input('amount','Amount per payment',x.amount,'number','min="0" step="0.01" required')}${select('frequency','Frequency',x.frequency,Object.keys(frequencies).map(v=>[v,v[0].toUpperCase()+v.slice(1)]))}${select('type','Classification',x.type,[['operating','Operating expense'],['capital','Capital expenditure']])}</div><div class="form-actions"><button value="cancel" class="secondary">Cancel</button><button class="primary">Save</button></div>`;f.onsubmit=ev=>{ev.preventDefault();Object.assign(x,Object.fromEntries(new FormData(f)));x.amount=num(x.amount);if(!e)p.expenses.push(x);save();$('#expenseDialog').close();render();toast('Expense saved')};$('#expenseDialog').showModal()}
function openValuation(p){const f=$('#valuationForm');f.innerHTML=`<div class="form-head"><h2>Add valuation</h2><button value="cancel" class="icon-btn">×</button></div><div class="form-grid">${input('date','Valuation date',new Date().toISOString().slice(0,10),'date','required')}${input('value','Estimated sale value',p.currentValue,'number','min="0" required')}${input('source','Source / valuer','Manual estimate','text','','full')}</div><div class="form-actions"><button value="cancel" class="secondary">Cancel</button><button class="primary">Save</button></div>`;f.onsubmit=ev=>{ev.preventDefault();const d=Object.fromEntries(new FormData(f));d.value=num(d.value);p.valuations.push(d);p.currentValue=d.value;p.valuationDate=d.date;save();$('#valuationDialog').close();render();toast('Valuation added')};$('#valuationDialog').showModal()}
function renderBackup(){$('#pageTitle').textContent='Backup & restore';$('#app').innerHTML=`<div class="panel"><h2>Your data</h2><p class="analysis">Property data is stored only in this browser. Export a backup before clearing browser data, changing phones, or replacing the GitHub Pages files.</p><div class="actions"><button class="primary" data-export>Export backup</button><label class="secondary" style="cursor:pointer">Import backup<input data-import type="file" accept="application/json" hidden></label></div></div><div class="panel"><h2>Privacy</h2><p class="analysis">There is no account, server, analytics service or automatic data feed in this version. Research links open external websites, but your property record is not sent to them.</p></div>`;$('[data-export]').onclick=exportData;$('[data-import]').onchange=importData}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`property-roi-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exported')}
function importData(e){const r=new FileReader();r.onload=()=>{try{const incoming=migrate(JSON.parse(r.result));if(!confirm(`Replace current data with ${incoming.properties.length} imported properties?`))return;state=incoming;save();route={name:'portfolio'};render();toast('Backup restored')}catch{alert('That file is not a valid Property ROI Tracker backup.')}};if(e.target.files[0])r.readAsText(e.target.files[0])}
function renderAbout(){$('#pageTitle').textContent='Guide';$('#app').innerHTML=`<div class="panel"><h2>How current ROE works</h2><div class="callout">Current ROE = (annual cash flow + annualised capital growth) ÷ net sale equity.</div><p class="analysis">Net sale equity is today’s estimated sale value, less the current loan and estimated selling costs. This makes the denominator the capital that could approximately be released by selling today—not the historic deposit or purchase price.</p><p class="analysis">Cash-only ROE excludes capital growth. Current ROE includes annualised growth from valuation history; if there is not enough history, it uses the market price-growth indicator you entered.</p></div><div class="panel"><h2>Important limits</h2><p class="analysis">Tax, capital-gains tax, depreciation, break fees and personal circumstances are excluded. The prospects score is a transparent directional summary of manually entered public indicators, not a valuation, prediction or recommendation. Check source dates and seek professional advice before acting.</p></div><div class="panel"><h2>Version</h2><p class="analysis">Property ROI Tracker v0.3.0 · local-first PWA · Australian dollars</p></div>`}

$('#headerAction').onclick=()=>openProperty();$('#backBtn').onclick=()=>{route={name:'portfolio'};render()};document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{route={name:b.dataset.route};render();scrollTo(0,0)});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
