function expenseDate(value){if(!value)return null;const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.valueOf())?null:d}
function localDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function dateText(value){const d=expenseDate(value);return d?new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',year:'numeric'}).format(d):'Not scheduled'}
function expenseStatus(e){if(e.paid&&e.frequency==='one-off')return {key:'paid',label:'Paid',days:null};const due=expenseDate(e.nextDueDate);if(!due)return {key:'unscheduled',label:'Date needed',days:null};const today=new Date();today.setHours(0,0,0,0);const days=Math.ceil((due-today)/86400000);if(days<0)return {key:'overdue',label:`${Math.abs(days)}d overdue`,days};if(days===0)return {key:'soon',label:'Due today',days};if(days<=num(e.reminderDays))return {key:'soon',label:`Due in ${days}d`,days};return {key:'scheduled',label:'Scheduled',days}}
function advanceExpense(e){const base=expenseDate(e.nextDueDate)||new Date(),today=new Date();today.setHours(0,0,0,0);if(base<today)base.setTime(today.getTime());if(e.frequency==='one-off'){e.paid=true;e.nextDueDate=''}else if(e.frequency==='weekly')base.setDate(base.getDate()+7);else if(e.frequency==='fortnightly')base.setDate(base.getDate()+14);else if(e.frequency==='monthly')base.setMonth(base.getMonth()+1);else if(e.frequency==='quarterly')base.setMonth(base.getMonth()+3);else if(e.frequency==='half-yearly')base.setMonth(base.getMonth()+6);else base.setFullYear(base.getFullYear()+1);e.lastPaidDate=localDateKey(new Date());if(!e.paid)e.nextDueDate=localDateKey(base)}

const originalOpenExpense=openExpense;
openExpense=function(p,e=null){
  originalOpenExpense(p,e);const f=$('#expenseForm'),x=e||{};
  const grid=f.querySelector('.form-grid');grid.insertAdjacentHTML('beforeend',`${input('payee','Payee / provider',x.payee||'','text','','full')}${input('nextDueDate','Next due date',x.nextDueDate||'','date')}${input('reminderDays','Remind me this many days before',x.reminderDays??14,'number','min="0" max="365"')}${input('lastPaidDate','Last paid date',x.lastPaidDate||'','date')}<div class="field full"><label for="expenseNotes">Notes / account reference</label><textarea id="expenseNotes" name="expenseNotes">${esc(x.notes||'')}</textarea></div>`);
  f.addEventListener('submit',()=>setTimeout(()=>{const d=Object.fromEntries(new FormData(f)),target=e||p.expenses.at(-1);if(!target)return;Object.assign(target,{payee:d.payee,nextDueDate:d.nextDueDate,reminderDays:num(d.reminderDays),lastPaidDate:d.lastPaidDate,notes:d.expenseNotes});save();render()},0),{once:true});
  f.querySelectorAll('[value="cancel"]').forEach(b=>{b.type='button';b.onclick=()=>$('#expenseDialog').close()});
};

const originalRenderPropertyForExpenses=renderProperty;
renderProperty=function(){
  originalRenderPropertyForExpenses();if(route.name!=='property')return;const p=state.properties.find(x=>x.id===route.id);if(!p)return;
  const baseScenario=document.querySelector('.scenario.featured small');if(baseScenario)baseScenario.textContent=`BASE · ${pct(forecastRate(p))}`;
  const oldHead=[...document.querySelectorAll('h3')].find(h=>h.textContent==='Expense register');if(oldHead){oldHead.closest('.section-head')?.classList.add('legacy-expenses');oldHead.closest('.panel')?.querySelectorAll('.expense-row').forEach(r=>r.classList.add('legacy-expenses'));}
  const items=[...p.expenses].sort((a,b)=>(a.nextDueDate||'9999').localeCompare(b.nextDueDate||'9999')),urgent=items.filter(e=>['overdue','soon'].includes(expenseStatus(e).key));
  const panel=document.createElement('section');panel.className='panel expense-schedule';panel.innerHTML=`<div class="panel-head"><div><span class="eyebrow">PAYABLE SCHEDULE</span><h2>Expenses and reminders</h2></div><button class="primary" data-schedule-add>+ Expense</button></div>${urgent.length?`<div class="reminder-banner"><b>${urgent.length} expense${urgent.length===1?'':'s'} need attention</b><span>${urgent.map(e=>`${esc(e.name)} · ${expenseStatus(e).label}`).join(' • ')}</span></div>`:`<div class="callout">Nothing is currently due within its reminder period.</div>`}<div class="expense-table-wrap"><table class="expense-table"><thead><tr><th>Expense</th><th>Amount</th><th>Frequency</th><th>Next due</th><th>Status</th><th>Last paid</th><th></th></tr></thead><tbody>${items.map(e=>{const st=expenseStatus(e);return `<tr><td data-label="Expense"><b>${esc(e.name)}</b><small>${esc(e.payee||e.type)}${e.notes?` · ${esc(e.notes)}`:''}</small></td><td data-label="Amount">${money(e.amount)}</td><td data-label="Frequency">${esc(e.frequency)}</td><td data-label="Next due">${dateText(e.nextDueDate)}</td><td data-label="Status"><span class="status ${st.key}">${st.label}</span></td><td data-label="Last paid">${dateText(e.lastPaidDate)}</td><td class="row-actions"><button data-pay-exp="${e.id}" class="primary" ${e.paid?'disabled':''}>Mark paid</button><button data-schedule-edit="${e.id}" class="secondary">Edit</button></td></tr>`}).join('')||'<tr><td colspan="7" class="empty">No expenses yet. Add the first bill or recurring cost.</td></tr>'}</tbody></table></div><p class="subtle">Reminders appear when you open the app. Marking a recurring expense paid records today and advances its next due date.</p>`;
  const prospects=[...document.querySelectorAll('h2')].find(h=>h.textContent==='Open-source market prospects')?.closest('.panel');(prospects||$('#app').lastElementChild).before(panel);
  const dock=document.createElement('div');dock.className='property-dock';dock.innerHTML='<button class="primary" data-dock-expense><span>＋</span>Expense</button><button class="secondary" data-dock-edit><span>✎</span>Edit property</button><button class="secondary" data-dock-value><span>⌁</span>Valuation</button>';$('#app').append(dock);
  panel.querySelector('[data-schedule-add]').onclick=()=>openExpense(p);dock.querySelector('[data-dock-expense]').onclick=()=>openExpense(p);dock.querySelector('[data-dock-edit]').onclick=()=>openProperty(p);dock.querySelector('[data-dock-value]').onclick=()=>openValuation(p);
  panel.querySelectorAll('[data-schedule-edit]').forEach(b=>b.onclick=()=>openExpense(p,p.expenses.find(e=>e.id===b.dataset.scheduleEdit)));panel.querySelectorAll('[data-pay-exp]').forEach(b=>b.onclick=()=>{const e=p.expenses.find(x=>x.id===b.dataset.payExp);advanceExpense(e);save();render();toast(`${e.name} marked paid`)});
};

const originalRenderPortfolioForExpenses=renderPortfolio;
renderPortfolio=function(){originalRenderPortfolioForExpenses();const due=[];state.properties.forEach(p=>p.expenses.forEach(e=>{const st=expenseStatus(e);if(['overdue','soon'].includes(st.key))due.push({p,e,st})}));if(!due.length)return;const alert=document.createElement('button');alert.className='portfolio-reminder';alert.innerHTML=`<span>●</span><div><b>${due.length} upcoming expense${due.length===1?'':'s'}</b><small>${due.slice(0,3).map(x=>`${esc(x.e.name)} · ${esc(x.p.address||'Property')} · ${x.st.label}`).join('<br>')}</small></div><strong>View ›</strong>`;alert.onclick=()=>{route={name:'property',id:due[0].p.id};render();setTimeout(()=>document.querySelector('.expense-schedule')?.scrollIntoView({behavior:'smooth'}),50)};$('#app').querySelector('.hero')?.after(alert)};

const originalRenderAboutForExpenses=renderAbout;
renderAbout=function(){originalRenderAboutForExpenses();const app=$('#app');app.innerHTML=app.innerHTML.replace('v0.4.0','v0.7.0');app.insertAdjacentHTML('beforeend','<div class="panel"><h2>Expense reminders</h2><p class="analysis">Upcoming and overdue payments appear on the portfolio and property pages when the tracker is opened. Mark Paid records the payment date and advances recurring schedules. These are in-app reminders; keep a separate calendar reminder for critical payments.</p></div><div class="panel"><h2>Capital-growth forecast</h2><p class="analysis">Enter historical suburb values and the number of years between them to calculate compound annual growth. Choose whether the forecast uses that historical CAGR or a manually entered suburb rate, then select the forecast period. Historical performance does not guarantee future performance.</p></div><div class="panel"><h2>Share portfolio</h2><p class="analysis">Record buy and sell allotments, brokerage, dividends and prices. Optional Alpha Vantage synchronisation adds recent daily prices and charts. Buy, Hold and Review indicators are rules-based decision support using your own assessments and price history—not personal financial advice.</p></div>')};

render();
