const originalOpenProperty=openProperty;
openProperty=function(p=null){
  originalOpenProperty(p);
  const f=$('#propertyForm'),x=p||{strategy:{}};
  const marketHead=[...f.querySelectorAll('.form-section')].at(-1);
  marketHead.insertAdjacentHTML('beforebegin',`${section('STRATEGY & FUTURE VALUE')}${input('growthConservative','Conservative growth %',x.strategy?.growthConservative??2,'number','step="0.1"')}${input('growthBase','Base growth %',x.strategy?.growthBase??5,'number','step="0.1"')}${input('growthOptimistic','Optimistic growth %',x.strategy?.growthOptimistic??7,'number','step="0.1"')}${input('strategyRentGrowth','Annual rent growth %',x.strategy?.rentGrowth??3,'number','step="0.1"')}${input('expenseGrowth','Annual expense growth %',x.strategy?.expenseGrowth??3,'number','step="0.1"')}${input('strategyInterestRate','Forecast interest rate %',x.strategy?.interestRate??p?.interestRate??6,'number','min="0" step="0.1"')}${input('annualDebtReduction','Annual debt reduction',x.strategy?.annualDebtReduction??p?.annualPrincipal??0,'number','min="0"')}${input('forecastYears','Forecast horizon (1–30 years)',x.strategy?.forecastYears??10,'number','min="1" max="30"')}${input('sellYear','Proposed sale year (0 = hold)',x.strategy?.sellYear??0,'number','min="0" max="30"')}${input('cgtRate','Effective tax on capital gain %',x.strategy?.cgtRate??0,'number','min="0" max="100" step="0.1"')}${input('redeployReturn','Redeployment return %',x.strategy?.redeployReturn??6,'number','step="0.1"')}${input('saleValueHaircut','Sale-value safety margin %',x.strategy?.saleValueHaircut??0,'number','min="0" max="50" step="0.1"')}`);
  f.addEventListener('submit',()=>setTimeout(()=>{const d=Object.fromEntries(new FormData(f)),target=p||state.properties.find(q=>q.id===route.id);if(!target)return;target.strategy={growthConservative:num(d.growthConservative),growthBase:num(d.growthBase),growthOptimistic:num(d.growthOptimistic),rentGrowth:num(d.strategyRentGrowth),expenseGrowth:num(d.expenseGrowth),interestRate:num(d.strategyInterestRate),annualDebtReduction:num(d.annualDebtReduction),forecastYears:Math.max(1,Math.min(30,num(d.forecastYears)||10)),sellYear:Math.max(0,num(d.sellYear)),cgtRate:num(d.cgtRate),redeployReturn:num(d.redeployReturn),saleValueHaircut:num(d.saleValueHaircut)};save();render()},0),{once:true});
  marketHead.insertAdjacentHTML('beforebegin',`${section('OPTIONAL DEVELOPMENT FEASIBILITY')}${select('developmentEnabled','Enable module',x.strategy?.developmentEnabled?'yes':'no',[['no','No'],['yes','Yes']])}${input('developmentMonths','Project duration (months)',x.strategy?.developmentMonths??24,'number','min="1"')}${input('developmentEndValue','End value / total revenue',x.strategy?.developmentEndValue??0,'number','min="0"')}${input('developmentCosts','Total development costs',x.strategy?.developmentCosts??0,'number','min="0"')}${input('developmentEquity','Equity contribution',x.strategy?.developmentEquity??0,'number','min="0"')}`);
  f.addEventListener('submit',()=>setTimeout(()=>{const d=Object.fromEntries(new FormData(f)),target=p||state.properties.find(q=>q.id===route.id);if(!target)return;Object.assign(target.strategy,{developmentEnabled:d.developmentEnabled==='yes',developmentMonths:num(d.developmentMonths),developmentEndValue:num(d.developmentEndValue),developmentCosts:num(d.developmentCosts),developmentEquity:num(d.developmentEquity)});save();render()},0),{once:true});
  f.querySelectorAll('[value="cancel"]').forEach(b=>{b.type='button';b.onclick=()=>$('#propertyDialog').close()});
};

const originalRenderAbout=renderAbout;
renderAbout=function(){originalRenderAbout();const panels=$('#app');panels.insertAdjacentHTML('beforeend','<div class="panel"><h2>Strategy forecasts</h2><p class="analysis">Growth, rent, expenses, interest, debt reduction, sale timing, tax and redeployment returns are editable assumptions. Conservative, base and optimistic cases are projections—not valuations. The optional development module is a high-level feasibility and depends on entering complete project costs.</p></div>');panels.innerHTML=panels.innerHTML.replace('v0.3.0','v0.4.0')};
